repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        entry: bazel run @rules_rust//:rustfmt --
        language: system
        pass_filenames: false
        types: [rust]

      - id: buildifier
        name: buildifier
        entry: tools/buildifier
        language: system
        require_serial: true
        files: (^|/)(BUILD|BUILD\.bazel|WORKSPACE|WORKSPACE\.bazel|MODULE\.bazel|.*\.bzl)$
