repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        entry: bazel run @rules_rust//tools/rustfmt:target_aware_rustfmt
        language: system
        types: [rust]
