name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Bazel test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}-${{ github.job }}
          repository-cache: true

      - name: Check buildifier
        run: tools/buildifier --check

      - name: Check rustfmt
        run: bazel build --config=rustfmt //...

      - name: Test extractor
        run: bazel test //...

      - name: Build binary
        run: bazel build //:compile_commands_extractor

      - name: Build refresh target
        run: bazel build //:refresh_all
